### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by RusseII** [Geczy/focusmate-autopilot#5]
Been using this extension for a while, love it except for a few issues! 

- [x] The bell sound is way too loud. It is jarring and always startles me. This increases my stress levels causing active harm.
- [x] Bell always rings twice. Once 20 seconds before and once right before the session ends.
- [x] I would like to be able to use my own custom sounds, or have a more relaxing and quiet sound. 
- [x] If both me and my partner are in a session early, the bell still plays. It should not play if already in a session.

**Comment by Geczy** [comment]
what if you join the session 10 minutes early? don't you still want the sound
